import os

from pathlib import Path
import sys


ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))


from dotenv import load_dotenv
load_dotenv()

OLLAMA_MODEL = os.getenv(
    "OLLAMA_MODEL",
    "llama3.2:1b",
)

OLLAMA_BASE_URL = os.getenv(
    "OLLAMA_BASE_URL",
    "http://localhost:11434",
)

TEMPERATURE = float(
    os.getenv(
        "TEMPERATURE",
        "0.2",
    )
)

OLLAMA_CONTEXT_WINDOW = int(
    os.getenv(
        "OLLAMA_CONTEXT_WINDOW",
        "8192",
    )
)

OLLAMA_MAX_OUTPUT_TOKENS = int(
    os.getenv(
        "OLLAMA_MAX_OUTPUT_TOKENS",
        "512",
    )
)
# Explicit Ollama context window.
#
# This is the maximum context we allow Ollama to use.
OLLAMA_CONTEXT_WINDOW = int(
    os.getenv(
        "OLLAMA_CONTEXT_WINDOW",
        "8192",
    )
)
# Maximum number of tokens generated by the model.
OLLAMA_MAX_OUTPUT_TOKENS = int(
    os.getenv(
        "OLLAMA_MAX_OUTPUT_TOKENS",
        "512",
    )
)
# ---------------------------------------------------------
# PostgreSQL
# ---------------------------------------------------------
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql+psycopg2://postgres:password@localhost:5432/travel_planner",
)

# ---------------------------------------------------------
# Conversation memory
# ---------------------------------------------------------

# Number of recent messages that are kept verbatim in the
# LLM context.
# 12 messages = approximately 6 user/assistant turns.
RECENT_MESSAGE_COUNT = int(
    os.getenv(
        "RECENT_MESSAGE_COUNT",
        "6",
    )
)
# When the number of stored messages exceeds this amount,
# older messages are compacted into the conversation summary.
SUMMARY_TRIGGER_MESSAGES = int(
    os.getenv(
        "SUMMARY_TRIGGER_MESSAGES",
        "12",
    )
)
# Approximate character budget for the summary.
# We deliberately keep this considerably smaller than the
# model context window.
SUMMARY_MAX_CHARS = int(
    os.getenv(
        "SUMMARY_MAX_CHARS",
        "6000",
    )
)

# Approximate character budget for the complete prompt.
# We use a conservative character/token approximation because
# llama3.2's exact tokenizer is not exposed through ChatOllama.
MAX_PROMPT_CHARS = int(
    os.getenv(
        "MAX_PROMPT_CHARS",
        "24000",
    )
)

# Authentication sessions
SESSION_TTL_HOURS = int(os.getenv("SESSION_TTL_HOURS", "24"))
SESSION_COOKIE_NAME = os.getenv("SESSION_COOKIE_NAME", "travel_planner_session")
